import { Category, FoodItem, User, Order, ActivityLog } from './types';
import bcrypt from 'bcryptjs';

// كلمات المرور الافتراضية
export const DEFAULT_PASSWORD_HASH = bcrypt.hashSync('123456', 8);
export const ADMIN_PASSWORD_HASH = bcrypt.hashSync('admin123', 8);
export const SUPER_ADMIN_HASH = bcrypt.hashSync('admin', 8);

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat-foul-falafel',
    name: 'فول وفلافل',
    slug: 'foul-falafel',
    icon: '🥙',
    image: '/images/sandwich-foul.jpg',
  },
  {
    id: 'cat-fries',
    name: 'بطاطس سوري',
    slug: 'fries',
    icon: '🍟',
    image: '/images/batates-souri.jpg',
  },
  {
    id: 'cat-cheese',
    name: 'جبنة بالطماطم',
    slug: 'cheese',
    icon: '🧀',
    image: '/images/gebna-tomatem.jpg',
  },
  {
    id: 'cat-pizza',
    name: 'بيتزا',
    slug: 'pizza',
    icon: '🍕',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-crepe',
    name: 'كريب',
    slug: 'crepe',
    icon: '🥞',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-feteer',
    name: 'فطير',
    slug: 'feteer',
    icon: '🥧',
    image: '/images/feteer-meshaltet.jpg',
  },
  {
    id: 'cat-shawarma',
    name: 'شاورما',
    slug: 'shawarma',
    icon: '🌯',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-fish',
    name: 'فسيخ ورنجة',
    slug: 'feseekh-renga',
    icon: '🐟',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
  },
];

export const SEED_FOOD_ITEMS: FoodItem[] = [
  // 1. فول وفلافل (فقط سندوتش فول وسندوتش فلافل)
  {
    id: 'food-foul-sand',
    categoryId: 'cat-foul-falafel',
    categoryName: 'فول وفلافل',
    name: 'سندوتش فول',
    description: 'سندوتش فول بلدي مدمس بالزيت والطحينة والتوابل الخاصة في العيش الطازج',
    price: 12,
    image: '/images/sandwich-foul.jpg',
    available: true,
  },
  {
    id: 'food-falafel-sand',
    categoryId: 'cat-foul-falafel',
    categoryName: 'فول وفلافل',
    name: 'سندوتش فلافل',
    description: 'سندوتش فلافل طعمية مقرمشة وسخنة بالسمسم مع الطحينة والسلطة الخضراء والمخلل',
    price: 12,
    image: '/images/sandwich-falafel.jpg',
    available: true,
  },

  // 2. بطاطس سوري (فقط بطاطس سوري)
  {
    id: 'food-batates-souri',
    categoryId: 'cat-fries',
    categoryName: 'بطاطس سوري',
    name: 'سندوتش بطاطس سوري',
    description: 'أصابع بطاطس مقرمشة ذهبية ملفوفة في خبز صاج سوري محمص مع صوص الثومية والمخلل',
    price: 25,
    image: '/images/batates-souri.jpg',
    available: true,
  },

  // 3. جبنة بالطماطم
  {
    id: 'food-cheese-tomato',
    categoryId: 'cat-cheese',
    categoryName: 'جبنة بالطماطم',
    name: 'سندوتش جبنة بالطماطم',
    description: 'جبنة فيتا بيضاء طبيعية متبلة بقطع الطماطم الطازجة وزيت الزيتون والنعناع في عيش بلدي دافئ',
    price: 18,
    image: '/images/gebna-tomatem.jpg',
    available: true,
  },

  // 4. بيتزا (جميع أنواع البيتزا كاملة)
  {
    id: 'food-pizza-margherita',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا مارجريتا كلاسيك',
    description: 'عجينة إيطالية هشة، صلصة طماطم بلدي، جبنة موزاريلا وفيرة، وريحان طازج',
    price: 70,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-cheese',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا فور تشيز (أربعة أجبان)',
    description: 'توليفة من الموزاريلا والجبنة الرومي والشيدر والجبنة الريكفورد الغنية',
    price: 90,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-vegetable',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا خضروات مشكلة',
    description: 'مغطاة بالفلفل الألوان، الزيتون المخلي، الطماطم الطازجة، البصل والمشروم',
    price: 75,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-chicken',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا فراخ رانش',
    description: 'قطع دجاج متبلة، صوص الرانش اللذيذ، فلفل ألوان، وجبنة موزاريلا مطاطية',
    price: 95,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-meat',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا لحمة مفرومة وسجق',
    description: 'لحم مفروم مع شرائح السجق البلدي والجبنة الموزاريلا والصلصة الإيطالية',
    price: 95,
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-pepperoni',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا بيبروني نيويورك',
    description: 'شرائح البيبروني البقري المقرمشة مع صلصة الطماطم الغنية وجبنة الموزاريلا',
    price: 95,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-seafood',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا سي فود جمبري وكاليماري',
    description: 'جمبري طازج وكاليماري متبل مع صوص الثوم والزعتر وجبنة الموزاريلا الفاخرة',
    price: 130,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-mix',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا ميكس لحوم وجبن سوبر سوبريم',
    description: 'مزيج اللحم المفروم والسجق والبيبروني والفلفل والزيتون والمشروم',
    price: 110,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-pizza-bbq',
    categoryId: 'cat-pizza',
    categoryName: 'بيتزا',
    name: 'بيتزا باربكيو تشيكن BBQ',
    description: 'قطع دجاج متبلة، صوص الباربكيو المدخن، بصل كراميل وجبنة موزاريلا',
    price: 95,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    available: true,
  },

  // 5. كريب (جميع أنواع الكريب كاملة)
  {
    id: 'food-crepe-chicken',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب كرانشي دجاج مقرمش',
    description: 'قطع كرسبي ستربس مقرمشة مع موزاريلا وبطاطس وكاتشب ومايونيز',
    price: 60,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-crepe-shawarma',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب شاورما فراخ بالثومية',
    description: 'شاورما فراخ متبلة مع صوص الثومية والجبنة الموزاريلا والمخلل',
    price: 65,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-crepe-meat',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب لحم برجر وبيكون',
    description: 'قطع لحم برجر مع جبنة شيدر وصوص الباربكيو والزيتون',
    price: 65,
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-crepe-cheese',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب ميكس جبن سايحة',
    description: 'كريب محشو بجبنة موزاريلا ورومي وشيدر مع زيتون وفلفل ألوان',
    price: 50,
    image: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-crepe-mix',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب ميكس لحوم ودجاج سوبر',
    description: 'ستربس دجاج مع سجق ولحم مفروم وجبنة موزاريلا وصوصات مميزة',
    price: 75,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-crepe-nutella',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب نوتيلا بالموز',
    description: 'نوتيلا أصلية وفيرة مع شرائح الموز الطازج وصوص الكراميل',
    price: 50,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-crepe-chocolate',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب شوكولاتة بالبندق',
    description: 'كريب رقيق محشو بصوص الشوكولاتة البلجيكية الغنية مع رشة بندق محمص',
    price: 40,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-crepe-fruit',
    categoryId: 'cat-crepe',
    categoryName: 'كريب',
    name: 'كريب ميكس فواكه طازجة',
    description: 'محشو بالفراولة والموز والكيوي مع الكريمة وصوص الشوكولاتة البيضاء',
    price: 55,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80',
    available: true,
  },

  // 6. فطير (جميع أنواع الفطير كاملة)
  {
    id: 'food-feteer-meshaltet',
    categoryId: 'cat-feteer',
    categoryName: 'فطير',
    name: 'فطير مشلتت فلاحي بالسمن البلدي',
    description: 'فطير مشلتت مورق ومخبوز بالسمن البلدي الفلاحي الصافي المقرمش من الخارج والطري من الداخل',
    price: 75,
    image: '/images/feteer-meshaltet.jpg',
    available: true,
  },
  {
    id: 'food-feteer-honey',
    categoryId: 'cat-feteer',
    categoryName: 'فطير',
    name: 'فطير بالعسل الأبيض والقشطة',
    description: 'قطع فطير مشلتت مورق يقدم مع طبق عسل نحل نقي وقشطة بلدي طازجة',
    price: 45,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-feteer-cheese',
    categoryId: 'cat-feteer',
    categoryName: 'فطير',
    name: 'فطير بالجبنة القديمة والمش',
    description: 'فطير فلاحي ساخن مع طبق جبنة مش بالطحينة والطماطم',
    price: 40,
    image: '/images/feteer-meshaltet.jpg',
    available: true,
  },
  {
    id: 'food-feteer-sweet',
    categoryId: 'cat-feteer',
    categoryName: 'فطير',
    name: 'فطير حلو بالسكر واللبن',
    description: 'فطيرة سخنة مسقية بالحليب الدافئ ومرشوشة بسكر بودرة ومكسرات وجوز هند',
    price: 45,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-feteer-savory',
    categoryId: 'cat-feteer',
    categoryName: 'فطير',
    name: 'فطير حادق ميكس سجق وجبن',
    description: 'فطير حادق محشي سجق بلدي وزيتون وفلفل وموزاريلا ورومي',
    price: 70,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-feteer-mix-honey-cheese',
    categoryId: 'cat-feteer',
    categoryName: 'فطير',
    name: 'فطير بالعسل والجبنة معاً',
    description: 'التوليفة الفلاحية الكاملة: فطيرة مع عسل أسود وطحينة وجبنة قديمة وعسل نحل',
    price: 55,
    image: '/images/feteer-meshaltet.jpg',
    available: true,
  },

  // 7. شاورما
  {
    id: 'food-shawarma-chicken',
    categoryId: 'cat-shawarma',
    categoryName: 'شاورما',
    name: 'شاورما فراخ سوري',
    description: 'شاورما دجاج متبلة بالبهارات السورية في خبز الصاج مع الثومية ومخلل الخيار المقرمش',
    price: 55,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-shawarma-meat',
    categoryId: 'cat-shawarma',
    categoryName: 'شاورما',
    name: 'شاورما لحمة مصري',
    description: 'شرائح لحم بقري متبلة مع بقدونس وبصل وطماطم وصوص طحينة في عيش كيزر طازج',
    price: 65,
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-shawarma-mix',
    categoryId: 'cat-shawarma',
    categoryName: 'شاورما',
    name: 'شاورما ميكس (فراخ + لحمة)',
    description: 'توليفة رائعة تجمع بين شاورما الدجاج وشاورما اللحم مع الثومية والطحينة',
    price: 70,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-shawarma-double',
    categoryId: 'cat-shawarma',
    categoryName: 'شاورما',
    name: 'شاورما دبل صاروخ',
    description: 'سندوتش حجم كبير جداً محشو بكمية مضاعفة من الشاورما مع بطاطس وثومية إضافية',
    price: 90,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    available: true,
  },

  // 8. فسيخ ورنجة
  {
    id: 'food-feseekh-dish',
    categoryId: 'cat-fish',
    categoryName: 'فسيخ ورنجة',
    name: 'طبق فسيخ نبروه ملوكي',
    description: 'فسيخ مخلي ونظيف مغطى بالزيت والليمون والشطة والبصل الأخضر والعيش البلدي',
    price: 110,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-renga-dish',
    categoryId: 'cat-fish',
    categoryName: 'فسيخ ورنجة',
    name: 'طبق رنجة هولندي مبطرفة مخلية',
    description: 'رنجة مدخنة فاخرة مخلية ومقطعة سلطة بالطحينة والطماطم والليمون وزيت الذرة',
    price: 65,
    image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-feseekh-sand',
    categoryId: 'cat-fish',
    categoryName: 'فسيخ ورنجة',
    name: 'سندوتش فسيخ مخلي',
    description: 'سندوتش فسيخ منظف متبل بالطحينة والليمون في عيش بلدي ساخن',
    price: 45,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'food-renga-sand',
    categoryId: 'cat-fish',
    categoryName: 'فسيخ ورنجة',
    name: 'سندوتش رنجة بالطحينة',
    description: 'سندوتش رنجة مدخنة مخلية مع شرائح الطماطم والبصل الأخضر وصوص الطحينة',
    price: 30,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
];

export const SEED_USERS: User[] = [
  // 1. حساب الإدارة المباشر (طلب المستخدم)
  {
    id: 'user-admin-main',
    name: 'إدارة فطرني شكراً',
    phone: '01000000000',
    passwordHash: SUPER_ADMIN_HASH, // كلمة المرور: admin
    role: 'ADMIN',
    createdAt: '2026-09-01T07:00:00.000Z',
  },
  // 2. مدير النظام
  {
    id: 'user-admin-mostafa',
    name: 'مصطفى محمد',
    phone: '01011112222',
    passwordHash: ADMIN_PASSWORD_HASH, // كلمة المرور: admin123
    role: 'ADMIN',
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  // 3. مسؤول التقديمات
  {
    id: 'user-admin-ahmed',
    name: 'د. أحمد إبراهيم',
    phone: '01033334444',
    passwordHash: ADMIN_PASSWORD_HASH, // كلمة المرور: admin123
    role: 'ADMIN',
    createdAt: '2026-09-01T08:30:00.000Z',
  },

  // 22 Students & Admissions Team Members
  { id: 'user-mariam', name: 'مريم خالد', phone: '01010001001', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T09:00:00.000Z' },
  { id: 'user-karim', name: 'كريم أحمد', phone: '01010001002', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T09:15:00.000Z' },
  { id: 'user-sara', name: 'سارة محمود', phone: '01010001003', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T09:30:00.000Z' },
  { id: 'user-mohamed-hassan', name: 'محمد حسن', phone: '01010001004', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T09:45:00.000Z' },
  { id: 'user-nour', name: 'نور علي', phone: '01010001005', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T10:00:00.000Z' },
  { id: 'user-omar', name: 'عمر طارق', phone: '01010001006', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T10:15:00.000Z' },
  { id: 'user-yasmin', name: 'ياسمين عبد الرحمن', phone: '01010001007', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T10:30:00.000Z' },
  { id: 'user-zeyad', name: 'زياد وائل', phone: '01010001008', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T10:45:00.000Z' },
  { id: 'user-habiba', name: 'حبيبة شريف', phone: '01010001009', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T11:00:00.000Z' },
  { id: 'user-youssef', name: 'يوسف إسلام', phone: '01010001010', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T11:15:00.000Z' },
  { id: 'user-aya', name: 'آية مصطفى', phone: '01010001011', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T11:30:00.000Z' },
  { id: 'user-hazem', name: 'حازم فتحي', phone: '01010001012', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T11:45:00.000Z' },
  { id: 'user-mayar', name: 'ميار حسام', phone: '01010001013', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T12:00:00.000Z' },
  { id: 'user-abdullah', name: 'عبد الله سعيد', phone: '01010001014', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T12:15:00.000Z' },
  { id: 'user-reem', name: 'ريم إيهاب', phone: '01010001015', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T12:30:00.000Z' },
  { id: 'user-belal', name: 'بلال ناصر', phone: '01010001016', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T12:45:00.000Z' },
  { id: 'user-salma', name: 'سلمى مجدي', phone: '01010001017', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T13:00:00.000Z' },
  { id: 'user-mazen', name: 'مازن عماد', phone: '01010001018', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T13:15:00.000Z' },
  { id: 'user-donia', name: 'دنيا خالد', phone: '01010001019', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T13:30:00.000Z' },
  { id: 'user-tarek', name: 'طارق نبيل', phone: '01010001020', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T13:45:00.000Z' },
  { id: 'user-malak', name: 'ملك عادل', phone: '01010001021', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T14:00:00.000Z' },
  { id: 'user-hamza', name: 'حمزة سامح', phone: '01010001022', passwordHash: DEFAULT_PASSWORD_HASH, role: 'USER', createdAt: '2026-09-02T14:15:00.000Z' },
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'order-101',
    orderNumber: 101,
    userId: 'user-admin-mostafa',
    userName: 'مصطفى محمد',
    userPhone: '01011112222',
    status: 'DELIVERED',
    notes: 'مكتب إدارة التقديمات - الدور الأرضي',
    createdAt: '2026-09-06T08:15:00.000Z',
    deliveredAt: '2026-09-06T08:45:00.000Z',
    items: [
      { id: 'item-1', foodItemId: 'food-foul-sand', foodName: 'سندوتش فول', foodImage: '/images/sandwich-foul.jpg', quantity: 2, price: 12 },
      { id: 'item-2', foodItemId: 'food-falafel-sand', foodName: 'سندوتش فلافل', foodImage: '/images/sandwich-falafel.jpg', quantity: 2, price: 12 },
      { id: 'item-3', foodItemId: 'food-batates-souri', foodName: 'سندوتش بطاطس سوري', foodImage: '/images/batates-souri.jpg', quantity: 1, price: 25 },
    ],
  },
  {
    id: 'order-102',
    orderNumber: 102,
    userId: 'user-mariam',
    userName: 'مريم خالد',
    userPhone: '01010001001',
    status: 'DELIVERED',
    notes: 'مكتب الاستقبال',
    createdAt: '2026-09-06T08:20:00.000Z',
    deliveredAt: '2026-09-06T08:50:00.000Z',
    items: [
      { id: 'item-4', foodItemId: 'food-foul-sand', foodName: 'سندوتش فول', foodImage: '/images/sandwich-foul.jpg', quantity: 1, price: 12 },
      { id: 'item-5', foodItemId: 'food-falafel-sand', foodName: 'سندوتش فلافل', foodImage: '/images/sandwich-falafel.jpg', quantity: 2, price: 12 },
      { id: 'item-6', foodItemId: 'food-cheese-tomato', foodName: 'سندوتش جبنة بالطماطم', foodImage: '/images/gebna-tomatem.jpg', quantity: 1, price: 18 },
    ],
  },
  {
    id: 'order-103',
    orderNumber: 103,
    userId: 'user-admin-ahmed',
    userName: 'د. أحمد إبراهيم',
    userPhone: '01033334444',
    status: 'DELIVERED',
    notes: 'غرفة الاجتماعات المركزية',
    createdAt: '2026-09-06T08:25:00.000Z',
    deliveredAt: '2026-09-06T08:55:00.000Z',
    items: [
      { id: 'item-7', foodItemId: 'food-feteer-meshaltet', foodName: 'فطير مشلتت فلاحي بالسمن البلدي', foodImage: '/images/feteer-meshaltet.jpg', quantity: 1, price: 75 },
      { id: 'item-8', foodItemId: 'food-feteer-honey', foodName: 'فطير بالعسل الأبيض والقشطة', foodImage: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80', quantity: 1, price: 45 },
    ],
  },
  {
    id: 'order-104',
    orderNumber: 104,
    userId: 'user-mohamed-hassan',
    userName: 'محمد حسن',
    userPhone: '01010001004',
    status: 'PENDING',
    notes: 'قاعة الحاسب الآلي 3',
    createdAt: '2026-09-06T09:00:00.000Z',
    deliveredAt: null,
    items: [
      { id: 'item-9', foodItemId: 'food-foul-sand', foodName: 'سندوتش فول', foodImage: '/images/sandwich-foul.jpg', quantity: 3, price: 12 },
      { id: 'item-10', foodItemId: 'food-falafel-sand', foodName: 'سندوتش فلافل', foodImage: '/images/sandwich-falafel.jpg', quantity: 3, price: 12 },
      { id: 'item-11', foodItemId: 'food-batates-souri', foodName: 'سندوتش بطاطس سوري', foodImage: '/images/batates-souri.jpg', quantity: 2, price: 25 },
    ],
  },
  {
    id: 'order-105',
    orderNumber: 105,
    userId: 'user-karim',
    userName: 'كريم أحمد',
    userPhone: '01010001002',
    status: 'PENDING',
    notes: 'مكتب شؤون الطلاب - دور ثاني',
    createdAt: '2026-09-06T09:05:00.000Z',
    deliveredAt: null,
    items: [
      { id: 'item-12', foodItemId: 'food-shawarma-chicken', foodName: 'شاورما فراخ سوري', foodImage: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80', quantity: 2, price: 55 },
      { id: 'item-13', foodItemId: 'food-crepe-chicken', foodName: 'كريب كرانشي دجاج مقرمش', foodImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80', quantity: 1, price: 60 },
      { id: 'item-14', foodItemId: 'food-cheese-tomato', foodName: 'سندوتش جبنة بالطماطم', foodImage: '/images/gebna-tomatem.jpg', quantity: 2, price: 18 },
    ],
  },
  {
    id: 'order-106',
    orderNumber: 106,
    userId: 'user-sara',
    userName: 'سارة محمود',
    userPhone: '01010001003',
    status: 'PENDING',
    notes: 'معمل اللغات - مبنى ب',
    createdAt: '2026-09-06T09:10:00.000Z',
    deliveredAt: null,
    items: [
      { id: 'item-15', foodItemId: 'food-pizza-margherita', foodName: 'بيتزا مارجريتا كلاسيك', foodImage: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80', quantity: 1, price: 70 },
      { id: 'item-16', foodItemId: 'food-crepe-nutella', foodName: 'كريب نوتيلا بالموز', foodImage: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80', quantity: 1, price: 50 },
    ],
  },
  {
    id: 'order-107',
    orderNumber: 107,
    userId: 'user-nour',
    userName: 'نور علي',
    userPhone: '01010001005',
    status: 'PENDING',
    notes: 'مكتب العلاقات العامة',
    createdAt: '2026-09-06T09:15:00.000Z',
    deliveredAt: null,
    items: [
      { id: 'item-17', foodItemId: 'food-foul-sand', foodName: 'سندوتش فول', foodImage: '/images/sandwich-foul.jpg', quantity: 2, price: 12 },
      { id: 'item-18', foodItemId: 'food-falafel-sand', foodName: 'سندوتش فلافل', foodImage: '/images/sandwich-falafel.jpg', quantity: 2, price: 12 },
      { id: 'item-19', foodItemId: 'food-batates-souri', foodName: 'سندوتش بطاطس سوري', foodImage: '/images/batates-souri.jpg', quantity: 2, price: 25 },
    ],
  },
  {
    id: 'order-108',
    orderNumber: 108,
    userId: 'user-omar',
    userName: 'عمر طارق',
    userPhone: '01010001006',
    status: 'PENDING',
    notes: 'مكتب الأمن الإداري',
    createdAt: '2026-09-06T09:20:00.000Z',
    deliveredAt: null,
    items: [
      { id: 'item-20', foodItemId: 'food-pizza-chicken', foodName: 'بيتزا فراخ رانش', foodImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80', quantity: 1, price: 95 },
      { id: 'item-21', foodItemId: 'food-crepe-chicken', foodName: 'كريب كرانشي دجاج مقرمش', foodImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80', quantity: 1, price: 60 },
    ],
  },
  {
    id: 'order-109',
    orderNumber: 109,
    userId: 'user-yasmin',
    userName: 'ياسمين عبد الرحمن',
    userPhone: '01010001007',
    status: 'PENDING',
    notes: 'المكتبة المركزية',
    createdAt: '2026-09-06T09:25:00.000Z',
    deliveredAt: null,
    items: [
      { id: 'item-22', foodItemId: 'food-cheese-tomato', foodName: 'سندوتش جبنة بالطماطم', foodImage: '/images/gebna-tomatem.jpg', quantity: 2, price: 18 },
      { id: 'item-23', foodItemId: 'food-feteer-sweet', foodName: 'فطير حلو بالسكر واللبن', foodImage: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80', quantity: 1, price: 45 },
    ],
  },
  {
    id: 'order-110',
    orderNumber: 110,
    userId: 'user-zeyad',
    userName: 'زياد وائل',
    userPhone: '01010001008',
    status: 'PENDING',
    notes: 'مبنى الورش التكنولوجية',
    createdAt: '2026-09-06T09:30:00.000Z',
    deliveredAt: null,
    items: [
      { id: 'item-24', foodItemId: 'food-batates-souri', foodName: 'سندوتش بطاطس سوري', foodImage: '/images/batates-souri.jpg', quantity: 3, price: 25 },
      { id: 'item-25', foodItemId: 'food-foul-sand', foodName: 'سندوتش فول', foodImage: '/images/sandwich-foul.jpg', quantity: 2, price: 12 },
    ],
  },
];

export const SEED_ACTIVITY_LOGS: ActivityLog[] = [
  { id: 'log-1', userId: 'user-admin-main', userName: 'إدارة فطرني شكراً', action: 'تهيئة وتحديث قائمة الطعام الرسمية', createdAt: '2026-09-06T08:00:00.000Z' },
  { id: 'log-2', userId: 'user-admin-mostafa', userName: 'مصطفى محمد', action: 'تسليم طلب #101 بنجاح', createdAt: '2026-09-06T08:45:00.000Z' },
  { id: 'log-3', userId: 'user-mariam', userName: 'مريم خالد', action: 'تسجيل استلام طلب #102', createdAt: '2026-09-06T08:50:00.000Z' },
  { id: 'log-4', userId: 'user-mohamed-hassan', userName: 'محمد حسن', action: 'طلب إفطار جديد #104', createdAt: '2026-09-06T09:00:00.000Z' },
];
